### ISSUE TITLE
Socket issue : `Cannot read property 'write' of null`

### ISSUE THREAD

**Issue by vekat** [iCrawl/discord-vscode#120]
So, I have found a bug that is triggered when you start VSCode without having Discord opened first.

It happens on my Ubuntu machine, but I do not know about other systems, so here's how I reproduce it:
1. Close Discord
2. Open VSCode with Discord Presence enabled
    1. Expectation: since Discord is closed, the RPC connection should fail
    2. Result: as expected, it fails and Discord Presence shows the "Reconnect" button
3. Click the "Reconnect" button
    1. Expectation: since Discord is closed, it should show the error message `Could not connect`
    2. Result: you will see the error message `Cannot read property 'write' of null`
4. Open Discord
5. Once again click the "Reconnect" button
    1. Expectation: since Discord is open, the RPC connection should succeed
    2. Result: you will see the error message `Cannot read property 'write' of null` again

This issue prevents Discord Presence's reconnect command from working as intended if you were to open Discord after VSCode even once.

I believe the error comes from the way the transport of the RPC client is being closed and then recreated between calls to `discord.reconnect` and on `close` events, leaving the transport without a socket.

If this is a confirmed bug, I think I know how to fix it.

_Originally posted by @vekat in https://github.com/iCrawl/discord-vscode/issues/107#issuecomment-439970036_

**Comment by KingDGrizzle** [comment]
I think i found out why. We set the close handler only after the rpc emits ready, which won't happen if Discord is closed on boot. The fix should be moving the `this._rpc.transport.once('close', ...)` outside the ready event handler on login and put it before logging in.

**Comment by vekat** [comment]
are you testing that fix right now, @KingDGrizzle ?

**Comment by KingDGrizzle** [comment]
Unfortunately not, as I am not home, but I should be able to test and PR it in about, I'd say ~4 hours

**Comment by i5o** [comment]
Hello there!
This issue also is happening to me:

```
[2021-05-23 21:28:21.923] [exthost] [error] TypeError: Cannot read property 'write' of null
	at IPCTransport.send (/home/ignacio/.vscode/extensions/icrawl.discord-vscode-5.6.3/dist/extension.js:2:22224)
	at /home/ignacio/.vscode/extensions/icrawl.discord-vscode-5.6.3/dist/extension.js:2:22311
	at new Promise (<anonymous>)
	at IPCTransport.close (/home/ignacio/.vscode/extensions/icrawl.discord-vscode-5.6.3/dist/extension.js:2:22268)
	at RPCClient.destroy (/home/ignacio/.vscode/extensions/icrawl.discord-vscode-5.6.3/dist/extension.js:2:15981)
	at disable (/home/ignacio/.vscode/extensions/icrawl.discord-vscode-5.6.3/dist/extension.js:2:143656)
	at /home/ignacio/.vscode/extensions/icrawl.discord-vscode-5.6.3/dist/extension.js:2:144123
	at E._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:107932)
	at E.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:108370)
	at l._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:12836)
	at l._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:12520)
	at l._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:11187)
	at l._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:9973)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:8074
	at fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at S.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15497)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:29764
	at fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at S.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15497)
	at t._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:20755)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17641
	at fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12862)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12210
	at Socket.v (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:13195)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) discord.reconnect
```

```
[default] [BUILD INFO] Release Channel: stable, Build Number: 85712, Version Hash: 10a988320d5a87262334534cc62304f174a8afce
f8fdc6974427540d7389.js:2 [default] [NATIVE INFO] host 0.0.14, modules: discord_desktop_core: 1, discord_erlpack: 1, discord_spellcheck: 1, discord_utils: 1, discord_voice: 3, discord_game_utils: 1, discord_rpc: 1
```

vscode
![image](https://user-images.githubusercontent.com/2650479/119281985-45b53680-bc0e-11eb-8a40-5ca38b48e993.png)

extension: v5.6.3

os: 
```
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 34 (Thirty Four)
Release:	34
Codename:	ThirtyFour
```

**Comment by Zensonaton** [comment]
Exactly same problem on Manjaro Linux.
